from typing import List, Dict, Any, Optional
import math

# from app.models.story_image import StoryImage # If we were passing StoryImage objects
# from app.core.config import settings # For MAX_IMAGES_PER_STORY etc.

class PageFormatter:
    """
    Formats raw story content and images into structured pages for a children's book experience.
    """
    def __init__(self, max_images_per_story: int = 2, words_per_page_target: int = 75):
        print("PageFormatter initialized.")
        self.max_images_per_story = max_images_per_story # Could come from settings
        self.words_per_page_target = words_per_page_target # Approximate target

    async def format_story_into_pages(
        self,
        story_title: str,
        raw_story_content: str,
        # image_prompts: List[str], # Prompts used for generation
        # generated_images_data: List[Dict[str, Any]], # List of {"prompt": "...", "base64_data": "..."} or similar
        # For mock, Gemini service gives paginated_content_stubs and image_prompts.
        # The actual images (base64) would be fetched/generated by ImagenService using these prompts.
        # Let's assume we get the paginated content stubs and a list of image objects (or dicts with id/base64)
        paginated_content_stubs: List[Dict[str, Any]], # From GeminiStoryService mock
        story_images: List[Dict[str, Any]] # List of {"id": "...", "image_placeholder_id": "...", "base64_data": "..."}
    ) -> List[Dict[str, Any]]:
        """
        Splits a story into readable pages and integrates images.

        Args:
            story_title: The title of the story.
            raw_story_content: The full raw text of the story. (Less used if stubs are good)
            paginated_content_stubs: List of dicts from story_generator, like:
                                     {"page_num": 1, "text": "...", "image_placeholder_id": "img_placeholder_1"}
            story_images: List of image dicts, e.g.,
                          [{"id": 1, "image_placeholder_id": "img_placeholder_1", "image_data_base64": "...", "image_prompt": "..."}, ...]
                          These are StoryImage objects in the real app.

        Returns:
            A list of page objects, each a dictionary with text, image details, layout etc.
            Example page:
            {
                "page_num": 1,
                "text": "Once upon a time...",
                "layout": "image_right", # "image_left", "text_only", "full_page_image"
                "image_id": 1, # ID of the StoryImage record
                "image_data_base64": "base64string..." # Actual image data for frontend
            }
        """
        print(f"PageFormatter: Formatting story '{story_title}'.")

        formatted_pages: List[Dict[str, Any]] = []

        # Create a mapping from image_placeholder_id to the actual image data
        image_map = {img.get("image_placeholder_id"): img for img in story_images if img.get("image_placeholder_id")}

        # Use paginated_content_stubs provided by the story generator
        for i, stub_page in enumerate(paginated_content_stubs):
            page_text = stub_page.get("text", "")
            page_num = stub_page.get("page_num", i + 1)
            image_placeholder_id = stub_page.get("image_placeholder_id")

            page_data: Dict[str, Any] = {
                "page_num": page_num,
                "text": page_text.strip(),
                "layout": "text_only", # Default layout
                "image_id": None,
                "image_data_base64": None,
            }

            if image_placeholder_id and image_placeholder_id in image_map:
                image_obj = image_map[image_placeholder_id]
                page_data["image_id"] = image_obj.get("id")
                page_data["image_data_base64"] = image_obj.get("image_data_base64")

                # Simple layout alternation for pages with images
                if (page_num -1) % 2 == 0: # 0, 2, 4... (page 1, 3, 5)
                    page_data["layout"] = "image_right"
                else: # 1, 3, 5... (page 2, 4, 6)
                    page_data["layout"] = "image_left"

            # Ensure text is not empty if no image, or adjust layout
            if not page_data["image_data_base64"] and not page_data["text"]:
                # Avoid completely empty pages if possible, unless intended as full image page
                if i == 0: # First page special handling
                    page_data["text"] = story_title # Use title if first page is empty
                else:
                    # Could try to pull more text or skip page, for now allow empty text
                    pass

            # If text is very short and there's an image, could consider 'image_focus' layout
            if page_data["image_data_base64"] and len(page_data["text"].split()) < 15:
                 # Potentially a different layout, or just keep as is.
                 pass


            formatted_pages.append(page_data)

        # Fallback logic if paginated_content_stubs are not good (e.g. all text on one page)
        # This part is more complex and involves smarter text splitting.
        # For now, we primarily rely on the stubs from GeminiStoryService.
        # If we were to do it from raw_story_content:
        # words = raw_story_content.split()
        # num_images_to_integrate = min(len(story_images), self.max_images_per_story)
        # num_text_pages_needed = math.ceil(len(words) / self.words_per_page_target)
        # total_pages_estimate = max(num_text_pages_needed, num_images_to_integrate) # Rough estimate

        # Simple distribution: try to put one image per N pages or one image per page up to max_images
        # This logic is highly dependent on desired book flow.
        # The current stub-based approach is simpler.

        if not formatted_pages: # Should not happen if stubs are provided
            print("Warning: No formatted pages could be generated. Returning empty list.")
            return []

        print(f"PageFormatter: Formatted into {len(formatted_pages)} pages.")
        return formatted_pages


# Example usage:
async def main():
    formatter = PageFormatter(max_images_per_story=2)

    mock_story_title = "The Brave Little Squirrel"
    mock_raw_content = "Once upon a time, there was a brave little squirrel named Squeaky. Squeaky loved adventures. One day, Squeaky decided to climb the tallest tree in the forest. It was a big challenge! Halfway up, Squeaky met a wise old owl. The owl gave Squeaky some nuts for energy. Finally, Squeaky reached the top and saw the whole forest. It was beautiful! Squeaky learned that bravery and a little help can achieve great things."

    # Simulate what story_generator might output
    mock_paginated_stubs = [
        {"page_num": 1, "text": "Once upon a time, there was a brave little squirrel named Squeaky. Squeaky loved adventures.", "image_placeholder_id": "img_placeholder_1"},
        {"page_num": 2, "text": "One day, Squeaky decided to climb the tallest tree in the forest. It was a big challenge! Halfway up, Squeaky met a wise old owl.", "image_placeholder_id": "img_placeholder_2"},
        {"page_num": 3, "text": "The owl gave Squeaky some nuts for energy. Finally, Squeaky reached the top and saw the whole forest. It was beautiful! Squeaky learned that bravery and a little help can achieve great things.", "image_placeholder_id": None},
    ]

    # Simulate what ImagenService + DB would provide
    mock_story_images = [
        {"id": "img_db_id_1", "image_placeholder_id": "img_placeholder_1", "image_data_base64": "base64_squeaky_start.png", "image_prompt": "Squeaky the squirrel starting an adventure."},
        {"id": "img_db_id_2", "image_placeholder_id": "img_placeholder_2", "image_data_base64": "base64_squeaky_and_owl.png", "image_prompt": "Squeaky meeting wise owl in tree."},
    ]

    pages = await formatter.format_story_into_pages(
        story_title=mock_story_title,
        raw_story_content=mock_raw_content, # Less used by this version of formatter
        paginated_content_stubs=mock_paginated_stubs,
        story_images=mock_story_images
    )

    print("\n--- Formatted Pages (Mock) ---")
    import json
    print(json.dumps(pages, indent=2))
    print("--- End of Formatted Pages ---")

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
